#pragma once

#include "neural_graph.hpp"

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <string>
#include <string_view>
#include <tuple>
#include <unordered_set>
#include <utility>
#include <vector>

namespace v0id::neural {

// A trace can contain either canonical clear values (for local/plain execution
// or after client-side decryption) or opaque ciphertext/container bytes returned
// by an encrypted evaluator. Known-answer integrity checkpoints are intentionally
// verified only against canonical clear values.
enum class NeuralTraceRepresentation : std::uint8_t {
    canonical_plaintext = 1,
    opaque_ciphertext = 2,
};

struct NeuralTraceEntry {
    std::uint64_t step_index{};
    std::string node_id;
    std::string port_name;
    NeuralPortRole role{NeuralPortRole::activation};
    NeuralNumericFormat format{NeuralNumericFormat::fixed16_16};
    TensorShape shape;
    NeuralTraceRepresentation representation{
        NeuralTraceRepresentation::canonical_plaintext};
    std::vector<std::uint8_t> value_bytes;

    // Commitment to this exact observed value at this exact graph endpoint and
    // logical execution step. Moving the same bytes to another node/port/step
    // produces a different commitment.
    NeuralDigest512 commitment512() const;
};

struct NeuralExecutionTrace {
    std::string protocol_id{"v0id-neural-execution-trace-v1"};
    NeuralDigest512 graph_digest{};
    NeuralDigest512 invocation_digest{};
    std::vector<NeuralTraceEntry> entries;

    // Structural validation only. This checks graph/invocation binding, endpoint
    // existence, output-port schemas and duplicate trace coordinates. It does
    // NOT prove that DENSE/BACKPROP/etc. arithmetic was executed correctly.
    void validate(const NeuralGraph& graph,
                  const NeuralInvocation& invocation) const;

    // Canonical commitment to the concrete trace. Entry vector order does not
    // affect the commitment; step_index carries logical execution ordering.
    NeuralDigest512 digest512(const NeuralGraph& graph,
                              const NeuralInvocation& invocation) const;
};

// Integrity checkpoints deliberately reference ordinary neural output ports.
// There is no CHECKSUM_NODE opcode here. A later hidden-integrity precompiler
// may build checksum lanes from normal DENSE/ACTIVATION/etc. nodes while keeping
// the client-side interpretation in this plan.
struct NeuralIntegrityCheckpoint {
    std::string label;
    std::uint64_t step_index{};
    std::string node_id;
    std::string port_name;
};

struct NeuralIntegrityPlan {
    std::string protocol_id{"v0id-neural-integrity-plan-v1"};
    std::string plan_id;
    std::uint64_t plan_version{1};
    std::vector<NeuralIntegrityCheckpoint> checkpoints;

    void validate(const NeuralGraph& graph) const;
    NeuralDigest512 digest512(const NeuralGraph& graph) const;
};

struct NeuralIntegrityObservation {
    std::string label;
    NeuralDigest512 entry_commitment{};

    bool operator==(const NeuralIntegrityObservation&) const = default;
};

// Client-side known-answer expectation for one integrity plan and invocation.
// In the future these expected values can be generated by a hidden neural
// checksum lane, challenge circuit, or other independently predictable probes.
struct NeuralIntegrityExpectation {
    std::string protocol_id{"v0id-neural-integrity-expectation-v1"};
    NeuralDigest512 graph_digest{};
    NeuralDigest512 invocation_digest{};
    NeuralDigest512 plan_digest{};
    std::vector<NeuralIntegrityObservation> expected;

    void validate(const NeuralGraph& graph,
                  const NeuralInvocation& invocation,
                  const NeuralIntegrityPlan& plan) const;
};

struct NeuralIntegrityReceipt {
    std::string protocol_id{"v0id-neural-integrity-receipt-v1"};
    NeuralDigest512 graph_digest{};
    NeuralDigest512 invocation_digest{};
    NeuralDigest512 trace_digest{};
    NeuralDigest512 plan_digest{};
    std::vector<NeuralIntegrityObservation> observed;

    // Validation re-derives every checkpoint commitment from the supplied trace.
    // A server cannot satisfy this API merely by attaching expected digests to a
    // trace whose actual checkpoint values differ.
    void validate(const NeuralGraph& graph,
                  const NeuralInvocation& invocation,
                  const NeuralExecutionTrace& trace,
                  const NeuralIntegrityPlan& plan) const;
};

// Extracts client-verifiable checkpoint commitments from a structurally valid
// trace. Checkpoint entries must be canonical_plaintext. For TFHE execution,
// the evaluator may return an opaque ciphertext trace first; the client must
// decrypt/normalize the selected trace values before building this receipt.
NeuralIntegrityReceipt make_neural_integrity_receipt(
    const NeuralGraph& graph,
    const NeuralInvocation& invocation,
    const NeuralExecutionTrace& trace,
    const NeuralIntegrityPlan& plan);

// Compares a validated receipt against independently known checkpoint values.
// This is a known-answer/probabilistic integrity mechanism, not a general proof
// of correct execution.
bool verify_neural_integrity_receipt(
    const NeuralGraph& graph,
    const NeuralInvocation& invocation,
    const NeuralExecutionTrace& trace,
    const NeuralIntegrityPlan& plan,
    const NeuralIntegrityExpectation& expectation,
    const NeuralIntegrityReceipt& receipt);

// Hook for the stronger development mode discussed in the architecture: a
// backend-specific verifier can replay every transition in a full trace. The
// plain fixed-point backend should implement this before TFHE lowering so it can
// serve as the semantic oracle. Merely implementing this interface does not turn
// a returned trace into a cryptographic proof.
class NeuralTraceSemanticVerifier {
public:
    virtual ~NeuralTraceSemanticVerifier() = default;
    virtual void verify_semantics(const NeuralGraph& graph,
                                  const NeuralInvocation& invocation,
                                  const NeuralExecutionTrace& trace) const = 0;
};

namespace integrity_detail {

inline constexpr std::size_t MAX_TRACE_ENTRIES = 1'000'000;
inline constexpr std::size_t MAX_TRACE_VALUE_BYTES = 512ull * 1024ull * 1024ull;
inline constexpr std::size_t MAX_INTEGRITY_CHECKPOINTS = 4096;

inline bool digest_all_zero(const NeuralDigest512& digest) {
    return std::all_of(digest.begin(), digest.end(),
                       [](std::uint8_t byte) { return byte == 0; });
}

inline void put_u64(std::vector<std::uint8_t>& out, std::uint64_t value) {
    for (int shift = 56; shift >= 0; shift -= 8)
        out.push_back(static_cast<std::uint8_t>((value >> shift) & 0xffu));
}

inline void put_string(std::vector<std::uint8_t>& out, std::string_view value) {
    put_u64(out, static_cast<std::uint64_t>(value.size()));
    out.insert(out.end(), value.begin(), value.end());
}

inline void put_digest(std::vector<std::uint8_t>& out,
                       const NeuralDigest512& digest) {
    out.insert(out.end(), digest.begin(), digest.end());
}

inline void put_blob(std::vector<std::uint8_t>& out,
                     const std::vector<std::uint8_t>& bytes) {
    put_u64(out, static_cast<std::uint64_t>(bytes.size()));
    out.insert(out.end(), bytes.begin(), bytes.end());
}

inline void validate_representation(NeuralTraceRepresentation representation) {
    switch (representation) {
        case NeuralTraceRepresentation::canonical_plaintext:
        case NeuralTraceRepresentation::opaque_ciphertext:
            return;
    }
    throw std::runtime_error("unknown neural trace representation");
}

inline const NeuralModuleNode& require_node(const NeuralGraph& graph,
                                            const std::string& node_id) {
    const auto it = std::find_if(graph.nodes.begin(), graph.nodes.end(),
                                 [&](const auto& node) {
                                     return node.id == node_id;
                                 });
    if (it == graph.nodes.end())
        throw std::runtime_error("neural trace references unknown node: " + node_id);
    return *it;
}

inline const NeuralPort& require_port(const NeuralGraph& graph,
                                      const std::string& node_id,
                                      const std::string& port_name) {
    const auto& node = require_node(graph, node_id);
    const auto it = std::find_if(node.ports.begin(), node.ports.end(),
                                 [&](const auto& port) {
                                     return port.name == port_name;
                                 });
    if (it == node.ports.end())
        throw std::runtime_error("neural trace references unknown port: " +
                                 node_id + "." + port_name);
    return *it;
}

inline std::string coordinate_key(std::uint64_t step,
                                  const std::string& node,
                                  const std::string& port) {
    return std::to_string(step) + "\x1f" + node + "\x1f" + port;
}

inline void validate_trace_entry(const NeuralGraph& graph,
                                 const NeuralTraceEntry& entry) {
    if (entry.node_id.empty() || entry.port_name.empty())
        throw std::runtime_error("neural trace entry requires node/port ids");
    if (entry.value_bytes.empty() ||
        entry.value_bytes.size() > MAX_TRACE_VALUE_BYTES)
        throw std::runtime_error("neural trace value byte size outside limit");

    validate_representation(entry.representation);
    entry.shape.validate();

    const auto& port = require_port(graph, entry.node_id, entry.port_name);
    if (port.direction != NeuralPortDirection::output)
        throw std::runtime_error("neural trace entries may reference output ports only");
    if (entry.role != port.role || entry.format != port.format ||
        entry.shape != port.shape)
        throw std::runtime_error("neural trace entry schema does not match graph port");
}

inline std::vector<NeuralTraceEntry> canonical_entries(
    const std::vector<NeuralTraceEntry>& entries) {
    auto sorted = entries;
    std::sort(sorted.begin(), sorted.end(), [](const auto& a, const auto& b) {
        return std::tie(a.step_index, a.node_id, a.port_name) <
               std::tie(b.step_index, b.node_id, b.port_name);
    });
    return sorted;
}

inline std::vector<NeuralIntegrityCheckpoint> canonical_checkpoints(
    const std::vector<NeuralIntegrityCheckpoint>& checkpoints) {
    auto sorted = checkpoints;
    std::sort(sorted.begin(), sorted.end(), [](const auto& a, const auto& b) {
        return a.label < b.label;
    });
    return sorted;
}

inline std::vector<NeuralIntegrityObservation> canonical_observations(
    const std::vector<NeuralIntegrityObservation>& observations) {
    auto sorted = observations;
    std::sort(sorted.begin(), sorted.end(), [](const auto& a, const auto& b) {
        return a.label < b.label;
    });
    return sorted;
}

inline void validate_observation_set(
    const std::vector<NeuralIntegrityObservation>& observations,
    const NeuralIntegrityPlan& plan,
    const char* what) {
    if (observations.size() != plan.checkpoints.size())
        throw std::runtime_error(std::string(what) +
                                 " observation count does not match integrity plan");

    std::unordered_set<std::string> labels;
    for (const auto& observation : observations) {
        if (observation.label.empty())
            throw std::runtime_error(std::string(what) + " has empty observation label");
        if (!labels.insert(observation.label).second)
            throw std::runtime_error(std::string(what) + " has duplicate observation label");
        if (digest_all_zero(observation.entry_commitment))
            throw std::runtime_error(std::string(what) + " has zero observation commitment");
    }

    for (const auto& checkpoint : plan.checkpoints) {
        if (!labels.contains(checkpoint.label))
            throw std::runtime_error(std::string(what) +
                                     " is missing integrity checkpoint label: " +
                                     checkpoint.label);
    }
}

inline const NeuralTraceEntry& require_checkpoint_entry(
    const NeuralExecutionTrace& trace,
    const NeuralIntegrityCheckpoint& checkpoint) {
    const auto it = std::find_if(trace.entries.begin(), trace.entries.end(),
                                 [&](const auto& entry) {
                                     return entry.step_index == checkpoint.step_index &&
                                            entry.node_id == checkpoint.node_id &&
                                            entry.port_name == checkpoint.port_name;
                                 });
    if (it == trace.entries.end())
        throw std::runtime_error("neural integrity checkpoint missing from execution trace: " +
                                 checkpoint.label);
    return *it;
}

inline const NeuralIntegrityObservation& require_observation(
    const std::vector<NeuralIntegrityObservation>& observations,
    const std::string& label) {
    const auto it = std::find_if(observations.begin(), observations.end(),
                                 [&](const auto& observation) {
                                     return observation.label == label;
                                 });
    if (it == observations.end())
        throw std::runtime_error("neural integrity observation missing label: " + label);
    return *it;
}

} // namespace integrity_detail

inline NeuralDigest512 NeuralTraceEntry::commitment512() const {
    using namespace integrity_detail;
    if (node_id.empty() || port_name.empty())
        throw std::runtime_error("cannot commit neural trace entry without node/port");
    if (value_bytes.empty() || value_bytes.size() > MAX_TRACE_VALUE_BYTES)
        throw std::runtime_error("cannot commit neural trace entry with invalid value size");
    validate_representation(representation);
    shape.validate();

    std::vector<std::uint8_t> canonical;
    put_string(canonical, "V0ID-NEURAL-TRACE-ENTRY-v1");
    put_u64(canonical, step_index);
    put_string(canonical, node_id);
    put_string(canonical, port_name);
    put_u64(canonical, static_cast<std::uint64_t>(role));
    put_u64(canonical, static_cast<std::uint64_t>(format));
    put_u64(canonical, static_cast<std::uint64_t>(representation));
    put_u64(canonical, static_cast<std::uint64_t>(shape.dimensions.size()));
    for (const auto dimension : shape.dimensions)
        put_u64(canonical, dimension);
    put_blob(canonical, value_bytes);
    return v0id::net::module_digest512(canonical);
}

inline void NeuralExecutionTrace::validate(
    const NeuralGraph& graph,
    const NeuralInvocation& invocation) const {
    using namespace integrity_detail;
    graph.validate();
    invocation.validate(graph);

    if (protocol_id != "v0id-neural-execution-trace-v1")
        throw std::runtime_error("unsupported neural execution trace protocol");
    if (graph_digest != graph.digest512())
        throw std::runtime_error("neural execution trace graph binding mismatch");
    if (invocation_digest != invocation.digest512(graph))
        throw std::runtime_error("neural execution trace invocation binding mismatch");
    if (entries.empty() || entries.size() > MAX_TRACE_ENTRIES)
        throw std::runtime_error("neural execution trace entry count outside limit");

    std::unordered_set<std::string> coordinates;
    coordinates.reserve(entries.size());
    for (const auto& entry : entries) {
        validate_trace_entry(graph, entry);
        const auto coordinate =
            coordinate_key(entry.step_index, entry.node_id, entry.port_name);
        if (!coordinates.insert(coordinate).second)
            throw std::runtime_error("duplicate neural execution trace coordinate");
    }
}

inline NeuralDigest512 NeuralExecutionTrace::digest512(
    const NeuralGraph& graph,
    const NeuralInvocation& invocation) const {
    using namespace integrity_detail;
    validate(graph, invocation);

    const auto sorted = canonical_entries(entries);
    std::vector<std::uint8_t> canonical;
    put_string(canonical, "V0ID-NEURAL-EXECUTION-TRACE-CANONICAL-v1");
    put_digest(canonical, graph_digest);
    put_digest(canonical, invocation_digest);
    put_u64(canonical, static_cast<std::uint64_t>(sorted.size()));
    for (const auto& entry : sorted)
        put_digest(canonical, entry.commitment512());
    return v0id::net::module_digest512(canonical);
}

inline void NeuralIntegrityPlan::validate(const NeuralGraph& graph) const {
    using namespace integrity_detail;
    graph.validate();
    if (protocol_id != "v0id-neural-integrity-plan-v1")
        throw std::runtime_error("unsupported neural integrity plan protocol");
    if (plan_id.empty() || plan_version == 0)
        throw std::runtime_error("neural integrity plan requires id/version");
    if (checkpoints.empty() || checkpoints.size() > MAX_INTEGRITY_CHECKPOINTS)
        throw std::runtime_error("neural integrity checkpoint count outside limit");

    std::unordered_set<std::string> labels;
    std::unordered_set<std::string> coordinates;
    for (const auto& checkpoint : checkpoints) {
        if (checkpoint.label.empty() || checkpoint.node_id.empty() ||
            checkpoint.port_name.empty())
            throw std::runtime_error("neural integrity checkpoint requires label/node/port");
        if (!labels.insert(checkpoint.label).second)
            throw std::runtime_error("duplicate neural integrity checkpoint label");

        const auto& port = require_port(graph, checkpoint.node_id,
                                        checkpoint.port_name);
        if (port.direction != NeuralPortDirection::output)
            throw std::runtime_error("neural integrity checkpoint must reference output port");

        const auto coordinate = coordinate_key(checkpoint.step_index,
                                               checkpoint.node_id,
                                               checkpoint.port_name);
        if (!coordinates.insert(coordinate).second)
            throw std::runtime_error("duplicate neural integrity checkpoint coordinate");
    }
}

inline NeuralDigest512 NeuralIntegrityPlan::digest512(
    const NeuralGraph& graph) const {
    using namespace integrity_detail;
    validate(graph);
    const auto sorted = canonical_checkpoints(checkpoints);

    std::vector<std::uint8_t> canonical;
    put_string(canonical, "V0ID-NEURAL-INTEGRITY-PLAN-CANONICAL-v1");
    put_digest(canonical, graph.digest512());
    put_string(canonical, plan_id);
    put_u64(canonical, plan_version);
    put_u64(canonical, static_cast<std::uint64_t>(sorted.size()));
    for (const auto& checkpoint : sorted) {
        put_string(canonical, checkpoint.label);
        put_u64(canonical, checkpoint.step_index);
        put_string(canonical, checkpoint.node_id);
        put_string(canonical, checkpoint.port_name);
    }
    return v0id::net::module_digest512(canonical);
}

inline void NeuralIntegrityExpectation::validate(
    const NeuralGraph& graph,
    const NeuralInvocation& invocation,
    const NeuralIntegrityPlan& plan) const {
    using namespace integrity_detail;
    invocation.validate(graph);
    plan.validate(graph);
    if (protocol_id != "v0id-neural-integrity-expectation-v1")
        throw std::runtime_error("unsupported neural integrity expectation protocol");
    if (graph_digest != graph.digest512())
        throw std::runtime_error("neural integrity expectation graph binding mismatch");
    if (invocation_digest != invocation.digest512(graph))
        throw std::runtime_error("neural integrity expectation invocation binding mismatch");
    if (plan_digest != plan.digest512(graph))
        throw std::runtime_error("neural integrity expectation plan binding mismatch");
    validate_observation_set(expected, plan, "neural integrity expectation");
}

inline void NeuralIntegrityReceipt::validate(
    const NeuralGraph& graph,
    const NeuralInvocation& invocation,
    const NeuralExecutionTrace& trace,
    const NeuralIntegrityPlan& plan) const {
    using namespace integrity_detail;
    trace.validate(graph, invocation);
    plan.validate(graph);
    if (protocol_id != "v0id-neural-integrity-receipt-v1")
        throw std::runtime_error("unsupported neural integrity receipt protocol");
    if (graph_digest != graph.digest512())
        throw std::runtime_error("neural integrity receipt graph binding mismatch");
    if (invocation_digest != invocation.digest512(graph))
        throw std::runtime_error("neural integrity receipt invocation binding mismatch");
    if (trace_digest != trace.digest512(graph, invocation))
        throw std::runtime_error("neural integrity receipt trace binding mismatch");
    if (plan_digest != plan.digest512(graph))
        throw std::runtime_error("neural integrity receipt plan binding mismatch");
    validate_observation_set(observed, plan, "neural integrity receipt");

    // Re-derive checkpoint commitments from the actual supplied trace rather
    // than trusting receipt.observed as server-provided metadata.
    for (const auto& checkpoint : plan.checkpoints) {
        const auto& entry = require_checkpoint_entry(trace, checkpoint);
        if (entry.representation != NeuralTraceRepresentation::canonical_plaintext)
            throw std::runtime_error(
                "neural integrity receipt requires client-normalized plaintext trace value: " +
                checkpoint.label);
        const auto& observation = require_observation(observed, checkpoint.label);
        if (observation.entry_commitment != entry.commitment512())
            throw std::runtime_error(
                "neural integrity receipt observation does not match execution trace: " +
                checkpoint.label);
    }
}

inline NeuralIntegrityReceipt make_neural_integrity_receipt(
    const NeuralGraph& graph,
    const NeuralInvocation& invocation,
    const NeuralExecutionTrace& trace,
    const NeuralIntegrityPlan& plan) {
    using namespace integrity_detail;
    trace.validate(graph, invocation);
    plan.validate(graph);

    NeuralIntegrityReceipt receipt;
    receipt.graph_digest = graph.digest512();
    receipt.invocation_digest = invocation.digest512(graph);
    receipt.trace_digest = trace.digest512(graph, invocation);
    receipt.plan_digest = plan.digest512(graph);
    receipt.observed.reserve(plan.checkpoints.size());

    for (const auto& checkpoint : plan.checkpoints) {
        const auto& entry = require_checkpoint_entry(trace, checkpoint);
        if (entry.representation != NeuralTraceRepresentation::canonical_plaintext)
            throw std::runtime_error(
                "neural integrity checkpoint requires client-normalized plaintext trace value: " +
                checkpoint.label);
        receipt.observed.push_back(
            NeuralIntegrityObservation{checkpoint.label, entry.commitment512()});
    }

    receipt.validate(graph, invocation, trace, plan);
    return receipt;
}

inline bool verify_neural_integrity_receipt(
    const NeuralGraph& graph,
    const NeuralInvocation& invocation,
    const NeuralExecutionTrace& trace,
    const NeuralIntegrityPlan& plan,
    const NeuralIntegrityExpectation& expectation,
    const NeuralIntegrityReceipt& receipt) {
    using namespace integrity_detail;
    expectation.validate(graph, invocation, plan);
    receipt.validate(graph, invocation, trace, plan);

    if (expectation.graph_digest != receipt.graph_digest ||
        expectation.invocation_digest != receipt.invocation_digest ||
        expectation.plan_digest != receipt.plan_digest)
        return false;

    return canonical_observations(expectation.expected) ==
           canonical_observations(receipt.observed);
}

} // namespace v0id::neural
