#pragma once

#include "series_generator.hpp"

#include <z3++.h>

#include <array>
#include <cstddef>
#include <cstdint>
#include <vector>

namespace v0id::integrity {

// Audit-only exact model of the real KMAC-based series generator over the
// exhaustive 8-bit reduced-root domain. This is deliberately NOT a symbolic
// implementation of SHA3/KMAC. Concrete outputs are generated by the production
// KmacSeriesGenerator and lifted into Z3 as a total root->series mapping.
using ReducedSeriesTable = std::array<std::vector<std::uint8_t>, 256>;

v0id::polymorph::SeriesSeed reduced_audit_root(std::uint8_t value);

ReducedSeriesTable build_reduced_series_table(
    const std::vector<std::uint8_t>& semantic_input,
    std::uint64_t epoch,
    std::size_t output_bytes);

// reduced_root_bv8 must be an 8-bit bit-vector. Each returned expression is an
// 8-bit byte selected from the exact production-generator table. The resulting
// formula is exact only for this declared reduced domain; it makes no claim to
// symbolically model full-width KMAC internals.
std::vector<z3::expr> z3_reduced_series(
    z3::context& ctx,
    const z3::expr& reduced_root_bv8,
    const ReducedSeriesTable& table,
    std::size_t output_bytes);

} // namespace v0id::integrity
